export const TAB_TYPES = [
  "chat",
  "model-chat",
  "canvas",
  "browser",
  "tasks",
  "editor",
  "research",
  "knowledge",
  "knowledge-graph",
  "memory",
  "terminal",
  "diff",
  "settings",
  "log",
  "media",
  "svg",
  "pdf",
  "notebook",
  "unsupported",
  "pomodoro",
  "mission-control",
  "artifacts",
] as const;

export type TabType = (typeof TAB_TYPES)[number];
