// A curated emoji set for the composer picker.
//
// Deliberately inline rather than a dependency: the full Unicode set with
// keywords is multiple megabytes, which is real weight in a desktop bundle for
// a feature that is "insert a smiley into a chat message". This covers the
// common vocabulary of a work chat, and swapping in a full dataset later is
// contained to this one module — nothing else imports the shape.
//
// Reactions are a different thing entirely: those are constrained to the
// server's `CHAT_REACTION_EMOJI` allowlist because a `react` outside it is a
// 400. Message text has no such limit, which is why this list can be broader.

export interface EmojiEntry {
  char: string;
  /** Space-separated search terms, all lowercase. */
  keywords: string;
}

export interface EmojiCategory {
  name: string;
  emoji: EmojiEntry[];
}

const e = (char: string, keywords: string): EmojiEntry => ({ char, keywords });

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: "Smileys",
    emoji: [
      e("😀", "grin happy smile"),
      e("😃", "smile happy joy"),
      e("😄", "smile laugh happy"),
      e("😁", "beam grin happy"),
      e("😆", "laugh lol haha"),
      e("😅", "sweat laugh relief"),
      e("🤣", "rofl laugh lol"),
      e("😂", "joy tears laugh lol"),
      e("🙂", "slight smile"),
      e("🙃", "upside down silly"),
      e("😉", "wink"),
      e("😊", "blush smile happy"),
      e("😇", "innocent angel halo"),
      e("🥰", "love hearts adore"),
      e("😍", "heart eyes love"),
      e("😘", "kiss blow"),
      e("😗", "kiss"),
      e("😋", "yum tasty tongue"),
      e("😛", "tongue cheeky"),
      e("🤪", "zany crazy wild"),
      e("🤨", "eyebrow suspicious skeptical"),
      e("🧐", "monocle inspect examine"),
      e("🤓", "nerd geek glasses"),
      e("😎", "cool sunglasses"),
      e("🥳", "party celebrate birthday"),
      e("😏", "smirk sly"),
      e("😒", "unamused meh"),
      e("😔", "pensive sad"),
      e("😴", "sleep zzz tired"),
      e("🤤", "drool"),
      e("😌", "relieved calm"),
      e("🤔", "thinking hmm consider"),
      e("🤗", "hug"),
      e("🤭", "oops giggle"),
      e("🤫", "shh quiet secret"),
      e("😐", "neutral meh"),
      e("😑", "expressionless blank"),
      e("😬", "grimace awkward yikes"),
      e("🙄", "eyeroll whatever"),
      e("😮", "open mouth wow surprise"),
      e("😯", "hushed surprise"),
      e("😲", "astonished shock"),
      e("😳", "flushed embarrassed"),
      e("🥺", "pleading puppy please"),
      e("😢", "cry sad tear"),
      e("😭", "sob cry bawl"),
      e("😤", "triumph steam frustrated"),
      e("😠", "angry mad"),
      e("😡", "rage furious mad"),
      e("🤯", "mind blown explode"),
      e("😱", "scream fear shock"),
      e("😨", "fearful scared"),
      e("😰", "anxious sweat"),
      e("😥", "sad disappointed"),
      e("🤒", "sick thermometer ill"),
      e("🤕", "hurt bandage injured"),
      e("🤢", "nauseated sick"),
      e("🥴", "woozy dizzy"),
      e("😵", "dizzy knocked out"),
      e("🥱", "yawn bored tired"),
    ],
  },
  {
    name: "Gestures",
    emoji: [
      e("👍", "thumbs up yes approve like +1"),
      e("👎", "thumbs down no disapprove -1"),
      e("👌", "ok perfect good"),
      e("🤌", "pinched italian chef"),
      e("✌️", "peace victory"),
      e("🤞", "fingers crossed luck hope"),
      e("🤟", "love you"),
      e("🤘", "rock horns"),
      e("🤙", "call me shaka"),
      e("👈", "point left"),
      e("👉", "point right"),
      e("👆", "point up"),
      e("👇", "point down"),
      e("☝️", "point up index"),
      e("✋", "raised hand stop"),
      e("🤚", "back of hand"),
      e("🖐️", "hand fingers splayed"),
      e("🖖", "vulcan spock"),
      e("👋", "wave hello hi bye"),
      e("🤝", "handshake deal agree"),
      e("🙏", "pray thanks please namaste"),
      e("✍️", "writing hand"),
      e("💪", "muscle strong flex"),
      e("👏", "clap applause bravo"),
      e("🙌", "raised hands celebrate praise"),
      e("👐", "open hands"),
      e("🤲", "palms up"),
      e("🫶", "heart hands love"),
    ],
  },
  {
    name: "People",
    emoji: [
      e("👀", "eyes look watch see"),
      e("👤", "silhouette person user"),
      e("👥", "people users"),
      e("🧑‍💻", "developer coder programmer"),
      e("👨‍💻", "man developer coder"),
      e("👩‍💻", "woman developer coder"),
      e("🧠", "brain smart think"),
      e("🦾", "mechanical arm robot"),
      e("🕵️", "detective investigate spy"),
      e("💁", "info desk person"),
      e("🤦", "facepalm"),
      e("🤷", "shrug dunno idk"),
      e("🙋", "raising hand question"),
      e("🙇", "bow sorry apologise"),
      e("🧘", "meditate calm zen"),
      e("🏃", "run running fast"),
      e("🚶", "walk"),
    ],
  },
  {
    name: "Work",
    emoji: [
      e("💻", "laptop computer code"),
      e("🖥️", "desktop computer monitor"),
      e("⌨️", "keyboard type"),
      e("🖱️", "mouse"),
      e("📱", "phone mobile"),
      e("💾", "save floppy disk"),
      e("💿", "disc cd"),
      e("📀", "dvd"),
      e("🗂️", "folders files organise"),
      e("📁", "folder"),
      e("📂", "open folder"),
      e("📄", "document page file"),
      e("📃", "page"),
      e("📊", "bar chart graph stats"),
      e("📈", "chart up growth increase"),
      e("📉", "chart down decrease loss"),
      e("📋", "clipboard list"),
      e("📌", "pin"),
      e("📎", "paperclip attach"),
      e("✂️", "scissors cut"),
      e("🔍", "search magnify find"),
      e("🔎", "search magnify"),
      e("🔐", "lock secure key"),
      e("🔑", "key access"),
      e("🔒", "lock closed private"),
      e("🔓", "unlock open"),
      e("⚙️", "gear settings config"),
      e("🔧", "wrench fix tool"),
      e("🔨", "hammer build"),
      e("🛠️", "tools build fix"),
      e("🐛", "bug issue defect"),
      e("🧪", "test experiment lab"),
      e("🧹", "broom clean sweep"),
      e("📦", "package box ship release"),
      e("🚀", "rocket launch ship deploy fast"),
      e("⏰", "alarm clock time"),
      e("⏳", "hourglass waiting time"),
      e("📅", "calendar date"),
      e("📆", "calendar"),
      e("✅", "check done complete yes"),
      e("❌", "cross no wrong fail"),
      e("⚠️", "warning caution alert"),
      e("🚧", "construction wip blocked"),
      e("📝", "memo note write"),
      e("✏️", "pencil edit write"),
      e("🗑️", "trash delete bin"),
      e("💡", "idea lightbulb tip"),
      e("🔔", "bell notification"),
      e("🔕", "mute bell off"),
      e("📢", "announce megaphone"),
      e("💬", "speech bubble comment chat"),
      e("💭", "thought bubble"),
      e("🗓️", "spiral calendar"),
    ],
  },
  {
    name: "Symbols",
    emoji: [
      e("❤️", "heart love red"),
      e("🧡", "orange heart"),
      e("💛", "yellow heart"),
      e("💚", "green heart"),
      e("💙", "blue heart"),
      e("💜", "purple heart"),
      e("🖤", "black heart"),
      e("🤍", "white heart"),
      e("💔", "broken heart"),
      e("💯", "hundred perfect score"),
      e("🔥", "fire hot lit"),
      e("⭐", "star favourite"),
      e("🌟", "glowing star sparkle"),
      e("✨", "sparkles magic shiny new"),
      e("⚡", "zap lightning fast"),
      e("💥", "boom collision"),
      e("💫", "dizzy star"),
      e("🎉", "party tada celebrate launch"),
      e("🎊", "confetti celebrate"),
      e("🏆", "trophy win award"),
      e("🥇", "gold medal first"),
      e("🎯", "target bullseye goal"),
      e("🧩", "puzzle piece"),
      e("🔗", "link chain url"),
      e("♻️", "recycle refresh"),
      e("🆕", "new"),
      e("🆗", "ok"),
      e("🔴", "red circle"),
      e("🟢", "green circle"),
      e("🟡", "yellow circle"),
      e("🔵", "blue circle"),
      e("⚪", "white circle"),
      e("⚫", "black circle"),
      e("🚫", "prohibited no ban"),
      e("❓", "question"),
      e("❗", "exclamation important"),
      e("➡️", "arrow right"),
      e("⬅️", "arrow left"),
      e("⬆️", "arrow up"),
      e("⬇️", "arrow down"),
      e("🔄", "refresh sync loop"),
    ],
  },
  {
    name: "Food & drink",
    emoji: [
      e("☕", "coffee tea break"),
      e("🍵", "tea green"),
      e("🍺", "beer"),
      e("🍻", "cheers beers"),
      e("🥂", "champagne cheers celebrate"),
      e("🍷", "wine"),
      e("🥤", "soda drink cup"),
      e("🧋", "bubble tea boba"),
      e("🍕", "pizza"),
      e("🍔", "burger"),
      e("🌮", "taco"),
      e("🍜", "noodles ramen"),
      e("🍣", "sushi"),
      e("🍩", "donut"),
      e("🍪", "cookie"),
      e("🎂", "cake birthday"),
      e("🍰", "cake slice"),
      e("🍫", "chocolate"),
      e("🍎", "apple"),
      e("🍌", "banana"),
      e("🥑", "avocado"),
    ],
  },
  {
    name: "Nature",
    emoji: [
      e("🐛", "bug caterpillar"),
      e("🐝", "bee"),
      e("🐞", "ladybug"),
      e("🦋", "butterfly"),
      e("🐙", "octopus"),
      e("🐳", "whale"),
      e("🐬", "dolphin"),
      e("🐢", "turtle slow"),
      e("🐍", "snake python"),
      e("🦀", "crab rust"),
      e("🐹", "hamster"),
      e("🐶", "dog puppy"),
      e("🐱", "cat kitten"),
      e("🦊", "fox"),
      e("🐻", "bear"),
      e("🐼", "panda"),
      e("🦁", "lion"),
      e("🐧", "penguin"),
      e("🦆", "duck"),
      e("🌵", "cactus"),
      e("🌲", "tree evergreen"),
      e("🌳", "tree"),
      e("🌸", "blossom flower spring"),
      e("🌻", "sunflower"),
      e("🌈", "rainbow"),
      e("☀️", "sun sunny"),
      e("🌙", "moon night"),
      e("⛅", "cloud sun weather"),
      e("🌧️", "rain"),
      e("❄️", "snow cold winter"),
      e("🌊", "wave ocean water"),
      e("🍂", "autumn leaves fall"),
    ],
  },
  {
    name: "Travel",
    emoji: [
      e("✈️", "plane flight travel"),
      e("🚗", "car drive"),
      e("🚕", "taxi"),
      e("🚌", "bus"),
      e("🚆", "train"),
      e("🚲", "bike bicycle"),
      e("🛴", "scooter"),
      e("🚢", "ship boat"),
      e("🏠", "house home"),
      e("🏢", "office building work"),
      e("🏭", "factory"),
      e("🗺️", "map"),
      e("🧭", "compass direction"),
      e("🌍", "earth globe world europe africa"),
      e("🌎", "earth globe americas"),
      e("🌏", "earth globe asia"),
      e("🗼", "tower"),
      e("🏔️", "mountain"),
      e("🏝️", "island beach vacation"),
      e("⛺", "tent camping"),
    ],
  },
];

/** Flat search across every category. Empty query returns nothing — the caller
 *  shows the categories instead. */
export function searchEmoji(query: string, limit = 60): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const out: EmojiEntry[] = [];
  for (const cat of EMOJI_CATEGORIES) {
    for (const entry of cat.emoji) {
      if (entry.keywords.includes(q)) {
        out.push(entry);
        if (out.length >= limit) return out;
      }
    }
  }
  return out;
}
