//! Full builds: determinism, persistence details, summaries, cancel.

use atlas_search::CancelToken;

use super::{dump, Project};
use crate::store::SCHEMA_VERSION;

const LIB: &str = "pub struct Store;\nimpl Store {\n    pub fn open() -> Self { Store }\n}\n";
const APP: &str =
    "import { x } from './x';\nexport function run() {}\nexport class App { start() {} }\n";
const TOOL: &str = "import os\n\ndef main():\n    pass\n";

fn fixture(p: &Project) {
    p.write("src/lib.rs", LIB)
        .write("web/app.ts", APP)
        .write("tool.py", TOOL);
}

#[test]
fn two_builds_identical_rows() {
    let p = Project::new();
    fixture(&p);
    let ix = p.built();
    let first = dump(&ix);
    assert!(first.len() > 6, "{first:?}");
    ix.full_build(&CancelToken::new(), &|_| {}).unwrap();
    assert_eq!(dump(&ix), first);
}

#[test]
fn build_is_independent_of_creation_order() {
    let a = Project::new();
    fixture(&a);
    let b = Project::new();
    b.write("tool.py", TOOL)
        .write("web/app.ts", APP)
        .write("src/lib.rs", LIB);
    assert_eq!(dump(&a.built()), dump(&b.built()));
}

#[test]
fn ids_follow_path_order() {
    let p = Project::new();
    fixture(&p);
    let ix = p.built();
    let rels: Vec<String> = ix
        .with_reader(|c| {
            let mut s = c.prepare("SELECT rel FROM files ORDER BY id")?;
            let rows = s.query_map([], |r| r.get(0))?;
            rows.collect()
        })
        .unwrap();
    assert_eq!(rels, ["src/lib.rs", "tool.py", "web/app.ts"]);
}

#[test]
fn status_reports_counts_and_needs_build() {
    let p = Project::new();
    fixture(&p);
    let ix = p.index();
    assert!(ix.status().unwrap().needs_full_build);
    let stats = ix.full_build(&CancelToken::new(), &|_| {}).unwrap();
    assert_eq!(stats.files, 3);
    let st = ix.status().unwrap();
    assert_eq!((st.files, st.symbols), (3, stats.symbols));
    assert!(!st.needs_full_build && st.built_at_ms > 0);
}

#[test]
fn index_lives_under_dot_atlas_and_git_excludes_it() {
    let p = Project::new();
    fixture(&p);
    let _ix = p.built();
    assert!(p.path(".atlas/code-index/index.db").is_file());
    let exclude = std::fs::read_to_string(p.path(".git/info/exclude")).unwrap();
    assert!(exclude.lines().any(|l| l == ".atlas/"), "{exclude}");
    // Idempotent: a second open adds nothing.
    drop(_ix);
    let _again = p.index();
    let after = std::fs::read_to_string(p.path(".git/info/exclude")).unwrap();
    assert_eq!(after, exclude);
    // The user's .gitignore is never touched.
    assert!(!p.path(".gitignore").exists());
}

#[test]
fn schema_version_mismatch_rebuilds_from_scratch() {
    let p = Project::new();
    fixture(&p);
    {
        let ix = p.built();
        ix.writer()
            .pragma_update(None, "user_version", SCHEMA_VERSION + 41)
            .unwrap();
    }
    let ix = p.index();
    let st = ix.status().unwrap();
    assert_eq!(st.files, 0);
    assert!(st.needs_full_build);
    let v: i64 = ix
        .writer()
        .query_row("PRAGMA user_version", [], |r| r.get(0))
        .unwrap();
    assert_eq!(v, SCHEMA_VERSION);
}

#[test]
fn cancelled_build_writes_nothing() {
    let p = Project::new();
    fixture(&p);
    let ix = p.built();
    let before = dump(&ix);
    p.write("src/more.rs", "pub fn more() {}\n");
    let cancel = CancelToken::new();
    cancel.cancel();
    assert!(matches!(
        ix.full_build(&cancel, &|_| {}),
        Err(crate::IndexError::Cancelled)
    ));
    assert_eq!(dump(&ix), before);
}

#[test]
fn status_counts_skips_by_reason() {
    let p = Project::new();
    p.write("vendor/lib/a.go", "package lib\nfunc A() {}\n")
        .write("api/v1/api.pb.go", "package v1\nfunc B() {}\n")
        .write(
            "gen/schema.ts",
            "// @generated by tool\nexport const s = 1;\n",
        )
        .write(
            "gen/models.go",
            "// Code generated by sqlc. DO NOT EDIT.\npackage gen\n",
        )
        .write("bin/blob.py", "x = 1\0\0\0\n")
        .write("main.go", "package main\nfunc main() {}\n");
    let ix = p.index();
    let stats = ix.full_build(&CancelToken::new(), &|_| {}).unwrap();
    assert_eq!(stats.files, 1);
    assert_eq!(stats.skipped.len(), 4);
    assert_eq!(
        ix.status().unwrap().skipped,
        [
            ("binary".to_string(), 1),
            ("generated_header".to_string(), 2),
            ("generated_name".to_string(), 1)
        ]
    );
}
