//! Discovery (sorted, pruned, skip reasons) and parallel processing.

use std::sync::Arc;

use atlas_search::CancelToken;

use crate::scan::{discover, process_all, Candidate, Outcome};
use crate::skip::{Rules, SkipReason};

use super::Project;

fn walk(p: &Project) -> (Vec<Candidate>, Vec<(String, SkipReason)>) {
    let rules = Arc::new(Rules::load(p.root()));
    let (cands, skipped, _) = discover(p.root(), p.root(), &rules, &CancelToken::new());
    (cands, skipped)
}

fn rels(cands: &[Candidate]) -> Vec<&str> {
    cands.iter().map(|c| c.rel.as_str()).collect()
}

fn label(o: &Outcome) -> String {
    match o {
        Outcome::Indexed(r) => format!("indexed {}", r.rel),
        Outcome::Unchanged { .. } => "unchanged".into(),
        Outcome::Skipped(r) => format!("skipped {}", r.label()),
        Outcome::Vanished => "vanished".into(),
        Outcome::Cancelled => "cancelled".into(),
    }
}

#[test]
fn discover_sorts_prunes_vendor_and_honours_gitignore() {
    let p = Project::new();
    p.write("web/b.ts", "export const b = 1;\n")
        .write("src/a.rs", "pub fn a() {}\n")
        .write("vendor/lib/x.go", "package lib\n")
        .write("api/api.pb.go", "package api\n")
        .write(".gitignore", "out/\n")
        .write("out/gen.ts", "export const g = 1;\n")
        .write("README.md", "# not code\n");
    let (kept, skipped) = walk(&p);
    assert_eq!(rels(&kept), ["src/a.rs", "web/b.ts"]);
    // vendor/ is pruned during the walk, but its source files are still
    // counted as skipped: an index missing a directory must say so.
    assert_eq!(
        skipped,
        [
            ("api/api.pb.go".to_string(), SkipReason::GeneratedName),
            ("vendor/lib/x.go".to_string(), SkipReason::Vendor),
        ]
    );
}

#[test]
fn atlasignore_reinclude_walks_into_vendor() {
    let p = Project::new();
    p.write(".atlasignore", "experiments/\n!vendor/ours/\n")
        .write("experiments/x.rs", "pub fn x() {}\n")
        .write("vendor/ours/a.rs", "pub fn ours() {}\n")
        .write("vendor/theirs/b.rs", "pub fn theirs() {}\n")
        .write("src/main.rs", "fn main() {}\n");
    let (kept, skipped) = walk(&p);
    assert_eq!(rels(&kept), ["src/main.rs", "vendor/ours/a.rs"]);
    // `experiments/` is pruned (no re-include reaches into it), and still
    // reported.
    assert_eq!(
        skipped,
        [
            ("experiments/x.rs".to_string(), SkipReason::AtlasIgnore),
            ("vendor/theirs/b.rs".to_string(), SkipReason::Vendor),
        ]
    );
}

#[test]
fn skips_large_and_minified() {
    let p = Project::new();
    p.write("src/ok.ts", "export function ok() {}\n");
    p.write(
        "src/app.bundle.js",
        &format!("export function a(){{{}}}\n", "var x=1;".repeat(2_000)),
    );
    p.write(
        "src/huge.ts",
        &format!("// big\n{}", "export const x = 1;\n".repeat(120_000)),
    );
    let (kept, skipped) = walk(&p);
    // Size is known from the stat: the 2 MB file is never read.
    assert_eq!(skipped, [("src/huge.ts".to_string(), SkipReason::TooLarge)]);
    let outcomes = process_all(&kept, &|_| None, &CancelToken::new());
    assert_eq!(
        outcomes.iter().map(label).collect::<Vec<_>>(),
        ["skipped minified", "indexed src/ok.ts"]
    );
}

#[test]
fn content_sniffs_binary_and_generated_headers() {
    let p = Project::new();
    p.write("bin/blob.py", "x = 1\0\0\0\n")
        .write(
            "gen/models.go",
            "// Code generated by sqlc. DO NOT EDIT.\npackage gen\n",
        )
        .write(
            "gen/schema.ts",
            "// @generated by tool\nexport const s = 1;\n",
        )
        .write("main.go", "package main\nfunc main() {}\n");
    let (kept, _) = walk(&p);
    let outcomes = process_all(&kept, &|_| None, &CancelToken::new());
    assert_eq!(
        outcomes.iter().map(label).collect::<Vec<_>>(),
        [
            "skipped binary",
            "skipped generated_header",
            "skipped generated_header",
            "indexed main.go"
        ]
    );
}

#[test]
fn process_all_keeps_path_order_and_honours_known_hashes() {
    let p = Project::new();
    for (i, n) in [3usize, 40, 1, 25, 7].iter().enumerate() {
        p.write(&format!("src/f{i}.rs"), &"pub fn f() {}\n".repeat(*n));
    }
    let (kept, _) = walk(&p);
    let outcomes = process_all(&kept, &|_| None, &CancelToken::new());
    let indexed: Vec<String> = outcomes
        .iter()
        .map(|o| match o {
            Outcome::Indexed(r) => r.rel.clone(),
            other => label(other),
        })
        .collect();
    assert_eq!(indexed, rels(&kept));
    // A matching stored hash means no re-parse.
    let hash = |i: usize| {
        std::fs::read(&kept[i].abs)
            .map(|b| blake3::hash(&b).as_bytes().to_vec())
            .ok()
    };
    let again = process_all(&kept, &hash, &CancelToken::new());
    assert!(again.iter().all(|o| matches!(o, Outcome::Unchanged { .. })));
    let cancel = CancelToken::new();
    cancel.cancel();
    assert!(process_all(&kept, &|_| None, &cancel)
        .iter()
        .all(|o| matches!(o, Outcome::Cancelled)));
}

#[test]
fn pruned_dirs_report_their_source_files_but_not_vcs_or_gitignored_ones() {
    let p = Project::new();
    p.write("src/a.rs", "pub fn a() {}\n")
        .write("web/node_modules/pkg/index.js", "module.exports = 1;\n")
        .write("web/node_modules/pkg/README.md", "# not code\n")
        .write("third_party/deep/vendor/x.go", "package x\n")
        .write(".gitignore", "target/\n")
        .write("target/debug/build.rs", "fn main() {}\n")
        .write(".git/hooks/pre_commit.py", "x = 0\n");
    let (kept, skipped) = walk(&p);
    assert_eq!(rels(&kept), ["src/a.rs"]);
    // Gitignored dirs were never the index's to skip; `.git` is not code.
    assert_eq!(
        skipped,
        [
            (
                "third_party/deep/vendor/x.go".to_string(),
                SkipReason::Vendor
            ),
            (
                "web/node_modules/pkg/index.js".to_string(),
                SkipReason::Vendor
            ),
        ]
    );
    assert_eq!(
        crate::skip::skipped_by_dir(&skipped),
        [
            ("vendor".to_string(), "third_party".to_string(), 1),
            ("vendor".to_string(), "web/node_modules".to_string(), 1),
        ]
    );
}
