//! Path rules, content sniffing and single-path gitignore checks.

use crate::skip::{sniff, IgnoreChain, Rules, SkipReason, MAX_FILE_BYTES};

use super::Project;

#[test]
fn generated_marker_must_be_a_leading_comment() {
    assert_eq!(
        sniff(b"// Code generated by x. DO NOT EDIT.\npackage a\n"),
        Some(SkipReason::GeneratedHeader)
    );
    assert_eq!(
        sniff(b"# @generated\nx = 1\n"),
        Some(SkipReason::GeneratedHeader)
    );
    // A string mentioning the marker, or a marker deep in the file, is not one.
    assert_eq!(sniff(b"const M = \"@generated\";\n"), None);
    let deep = format!("{}// DO NOT EDIT\n", "fn a() {}\n".repeat(10));
    assert_eq!(sniff(deep.as_bytes()), None);
}

#[test]
fn sniff_flags_binary_minified_and_oversized() {
    assert_eq!(sniff(b"x = 1\0\0\n"), Some(SkipReason::Binary));
    let minified = format!("function a(){{{}}}\n", "var x=1;".repeat(2_000));
    assert_eq!(sniff(minified.as_bytes()), Some(SkipReason::Minified));
    let big = vec![b'a'; usize::try_from(MAX_FILE_BYTES).unwrap() + 1];
    assert_eq!(sniff(&big), Some(SkipReason::TooLarge));
    assert_eq!(sniff(b"pub fn ok() {}\n"), None);
}

#[test]
fn atlasignore_excludes_and_reincludes() {
    let p = Project::new();
    p.write(".atlasignore", "experiments/\n!vendor/ours/\n");
    let rules = Rules::load(p.root());
    assert_eq!(
        rules.path_verdict("experiments/x.rs"),
        Some(SkipReason::AtlasIgnore)
    );
    assert_eq!(
        rules.path_verdict("vendor/theirs/b.rs"),
        Some(SkipReason::Vendor)
    );
    assert_eq!(rules.path_verdict("vendor/ours/a.rs"), None);
    assert_eq!(
        rules.path_verdict("api/v1/api.pb.go"),
        Some(SkipReason::GeneratedName)
    );
    assert_eq!(
        rules.path_verdict("web/app.min.js"),
        Some(SkipReason::GeneratedName)
    );
    assert_eq!(rules.path_verdict("src/main.rs"), None);
    // A re-include keeps skipped directories walkable; without one they are pruned.
    assert!(!rules.prune_dir("vendor"));
    let plain = Project::new();
    let rules = Rules::load(plain.root());
    assert!(
        rules.prune_dir("vendor") && rules.prune_dir("web/node_modules") && !rules.prune_dir("src")
    );
}

#[test]
fn ignore_chain_follows_nested_gitignores_and_info_exclude() {
    let p = Project::new();
    p.write(".gitignore", "build/\n*.log.ts\n!keep.log.ts\n")
        .write("pkg/.gitignore", "gen/\n");
    std::fs::write(p.path(".git/info/exclude"), "secret/\n").unwrap();
    let chain = IgnoreChain::new(p.root());
    assert!(chain.is_ignored("build/out.ts", false));
    assert!(chain.is_ignored("a.log.ts", false));
    assert!(!chain.is_ignored("keep.log.ts", false));
    assert!(chain.is_ignored("pkg/gen/x.ts", false));
    assert!(
        !chain.is_ignored("gen/x.ts", false),
        "pkg/.gitignore applies under pkg/ only"
    );
    assert!(chain.is_ignored("secret/k.ts", false));
    assert!(chain.is_ignored("build", true));
    assert!(!chain.is_ignored("src/main.ts", false));
}

#[test]
fn a_project_inside_a_repository_honours_ignores_above_it() {
    let p = Project::new();
    p.write(".gitignore", "build/\n*.gen.ts\n")
        .write("app/src/main.ts", "export {}\n");
    std::fs::write(p.path(".git/info/exclude"), "/app/tmp/\n").unwrap();
    let chain = IgnoreChain::new(&p.path("app"));
    assert!(chain.is_ignored("build/x.ts", false));
    assert!(chain.is_ignored("src/a.gen.ts", false));
    assert!(
        chain.is_ignored("tmp/a.ts", false),
        "info/exclude is anchored at the repository top"
    );
    assert!(!chain.is_ignored("src/main.ts", false));
}
